<?php
/******************************************
PT_BR
Admin Category Language
******************************************/

$lang['categories']					= 'Categorias';
$lang['error_must_select']			= 'Escolha Uma Categoria Para Organizar';
$lang['error_not_found']			= 'Categoria Não Encontrada.';
$lang['organize_category']			= 'Organizar "%s" Categoria';
$lang['organize']					= 'Organizar';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Cadastro - Categoria';
$lang['name']						= 'Nome';
$lang['slug']						= 'Slug';
$lang['description']				= 'Descrição';
$lang['excerpt']					= 'Resumo';
$lang['sequence']					= 'Sequência';
$lang['image']						= 'Imagem';
$lang['seo_title']					= 'SEO - Título';
$lang['meta']						= 'Meta Data';
$lang['message_category_saved']		= 'Categoria Salva!';
$lang['error_file_upload']			= '<p>Você Não Selecionou Um Arquivo Para Upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'Categoria Excluída.';
$lang['current_file']				= 'Arquivo Atual';
$lang['confirm_delete_category']	= 'Tem Certeza que Deseja Deletar Esta Categoria?';
$lang['add_new_category']			= 'Adicionar Nova Categoria';
$lang['top_level_category']         = 'Categoria de Nivel Superior';
$lang['no_categories']				= 'Não Há Categorias';
$lang['attributes']					= 'Atributos';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Padrão';
$lang['meta_data_description']		= 'ex. &lt;meta name="descrição" content="Produtos que ajudarão você" /&gt;';
$lang['drag_and_drop']				= 'Arraste e Solte Os Produtos Na Ordem Que Você Gostaria que Aparecessem.';
$lang['sku']						= 'Codigo';
$lang['price']						= 'Preço';
$lang['sale']						= 'Venda';
$lang['max_file_size']				= 'Limite';