version: "3.1"
services:
    db:
        image: mysql:5.7
        container_name: db
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: database
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./mysql/data:/var/lib/mysql
    webserver:
        image: nginx:alpine
        container_name: webserver
        volumes:
          - ../:/var/www/html
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8080:80"
        links:
          - db
          - php-fpm
    php-fpm:
        build: php-fpm
        container_name: php-fpm
        volumes:
          - ../:/var/www/html
          - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
          - ./php-fpm/php-ini-cli-timezone.ini:/etc/php/7.4/cli/conf.d/99-timezone.ini
        links:
          - db